"""Scratch entry point for native (Rust) debugging in RustRover.

Generated by the "Maturin for RustRover" plugin. It imports a compiled PyO3
module, prints its PID, and waits so you can 'Attach to Process' in RustRover
and set breakpoints in src/lib.rs *before* the Rust function is called.

    python debug_entry.py            # defaults to stage_01_hello / hello("world")
    python debug_entry.py stage_01_hello world
"""
import importlib, os, sys

mod_name = sys.argv[1] if len(sys.argv) > 1 else "stage_01_hello"
arg      = sys.argv[2] if len(sys.argv) > 2 else "world"

mod = importlib.import_module(mod_name)
print(f"PID = {os.getpid()}")
input("Attach RustRover's debugger to this PID, set breakpoints, then press Enter… ")
print(mod.hello(arg))   # adjust this call for other stages
